// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {journal} from '../models';
import {service} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetEntries():Promise<Array<journal.Entry>>;

export function GetEntry(arg1:string):Promise<journal.Entry>;

export function GetStats():Promise<service.Stats>;

export function GetToday():Promise<journal.Entry>;

export function ReadEntry(arg1:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function WriteEntry(arg1:string,arg2:string):Promise<void>;
