// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetToday() {
  return window['go']['main']['App']['GetToday']();
}

export function ReadEntry(arg1) {
  return window['go']['main']['App']['ReadEntry'](arg1);
}

export function WriteEntry(arg1, arg2) {
  return window['go']['main']['App']['WriteEntry'](arg1, arg2);
}
